import Head from 'next/head';
import type { NextPage } from 'next';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Docploy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav>
        <h1>Nav</h1>
      </nav>

      <main>
        <h1>Main</h1>
      </main>

      <footer>
        <h1>Footer</h1>
      </footer>
    </div>
  );
};

export default Home;
